# Threshold for large transactions (in tokens)
large_tx_threshold: 1000000

# API timeout in seconds
api_timeout: 30

# Update interval in minutes
update_interval: 15

# Maximum transactions to keep per address
max_transactions_per_address: 100

# Token addresses and IDs
tokens:
  USDT:
    ethereum: "0xdAC17F958D2ee523a2206206994597C13D831ec7"
    bsc: "0x55d398326f99059fF775485246999027B3197955"
    defillama_id: "USDT"
  USDC:
    ethereum: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
    bsc: "0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d"
    defillama_id: "USDC"
  BUSD:
    ethereum: "0x4Fabb145d64652a948d72533023f6E7A623C7C53"
    bsc: "0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56"
    defillama_id: "BUSD"

# API rate limiting delays (in seconds)
rate_limits:
  ethereum: 1
  bsc: 2

# Minimum value (in USD) for whale transaction alerts
whale_alert_threshold: 1000000 